// Service Data Definitions
// This file contains all the pharmacy service configurations and calculations

// Generic calculation for most services
export const standardCalc = (c, p, pfc, pfp, fr, tf) => {
    const curVal = (fr + pfc) * c * tf;
    const addVal = (fr + pfp) * (p - c) * tf + (pfp - pfc) * c * tf;
    return [curVal, addVal];
};

// Service data organized by category
export const servicesData = {
    part1: [
        {
            id: "daa-eligible",
            name: "DAA - eligible",
            fundedRateDesc: "$6.17 /wk",
            fundedRate: 6.17,
            patientFeeCurrent: 5,
            patientFeePotential: 7.7,
            unit: "Patients",
            timeFactor: 52,
            currentVol: 80,
            potentialVol: 90,
            calc: standardCalc,
        },
        {
            id: "daa-private",
            name: "DAA - private",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 5,
            patientFeePotential: 7.7,
            unit: "Patients",
            timeFactor: 52,
            currentVol: 10,
            potentialVol: 20,
            calc: standardCalc,
        },
        {
            id: "idaa",
            name: "IDAA",
            fundedRateDesc: "$11.60 /wk",
            fundedRate: 11.6,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients",
            timeFactor: 52,
            currentVol: 2,
            potentialVol: 20,
            calc: standardCalc,
        },
        {
            id: "staged-supply",
            name: "Staged Supply - eligible",
            fundedRateDesc: "$13.61 /wk (avg)",
            fundedRate: 13.61,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients",
            timeFactor: 52,
            currentVol: 3,
            potentialVol: 15,
            calc: standardCalc,
        },
        {
            id: "medschecks",
            name: "MedsChecks & Diabetes MedsChecks",
            isCombined: true,
            fields: [
                {
                    id: "mc",
                    name: "MedsChecks",
                    fundedRateDesc: "$66.53",
                    fundedRate: 66.53,
                    currentVol: 5,
                    potentialVol: 10,
                },
                {
                    id: "dmc",
                    name: "Diabetes MedsChecks",
                    fundedRateDesc: "$99.79",
                    fundedRate: 99.79,
                    currentVol: 1,
                    potentialVol: 10,
                },
            ],
            unit: "per month",
            timeFactor: 12,
            calc: (vols, tf) => {
                let curVal = 0;
                let addVal = 0;
                Object.values(vols).forEach((v) => {
                    curVal += v.fr * v.c;
                    addVal += v.fr * (v.p - v.c);
                });
                return [curVal * tf, addVal * tf];
            },
        },
        {
            id: "hmr",
            name: "HMRs",
            fundedRateDesc: "$222.77",
            fundedRate: 222.77,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "/month",
            timeFactor: 12,
            currentVol: 1,
            potentialVol: 30,
            calc: standardCalc,
        },
        {
            id: "hmr-f1",
            name: "HMR 1st Follow Up",
            fundedRateDesc: "$111.39",
            fundedRate: 111.39,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 15,
            calc: standardCalc,
        },
        {
            id: "hmr-f2",
            name: "HMR 2nd Follow Up",
            fundedRateDesc: "$55.70",
            fundedRate: 55.7,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 7,
            calc: standardCalc,
        },
        {
            id: "rmmr",
            name: "RMMRs",
            fundedRateDesc: "$112.65",
            fundedRate: 112.65,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients/yr",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 75,
            calc: standardCalc,
        },
        {
            id: "rmmr-f1",
            name: "RMMRs 1st Follow Up",
            fundedRateDesc: "$56.33",
            fundedRate: 56.33,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients/yr",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 15,
            calc: standardCalc,
        },
        {
            id: "rmmr-f2",
            name: "RMMRs 2nd Follow Up",
            fundedRateDesc: "$28.16",
            fundedRate: 28.16,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients/yr",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 5,
            calc: standardCalc,
        },
        {
            id: "qum",
            name: "Quality Use of Medicines",
            fundedRateDesc: "$125 base + $12.50/bed /qtr",
            fundedRate: 12.5,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Beds",
            timeFactor: 4,
            currentVol: 0,
            potentialVol: 75,
            calc: (c, p, pfc, pfp, fr, tf) => {
                const base = 125;
                const curVal = c > 0 ? (base + fr * c) * tf : 0;
                const potVal = p > 0 ? (base + fr * p) * tf : 0;
                return [curVal, potVal - curVal];
            },
        },
        {
            id: "odt-oral",
            name: "ODT supply (oral)",
            fundedRateDesc: "$5.66 /day",
            fundedRate: 5.66 * 7,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients",
            timeFactor: 52,
            currentVol: 5,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "odt-weekly",
            name: "ODT WEEKLY admin (injectable)",
            fundedRateDesc: "$22.15 /injection",
            fundedRate: 22.15,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients",
            timeFactor: 52,
            currentVol: 0,
            potentialVol: 1,
            calc: standardCalc,
        },
        {
            id: "odt-monthly",
            name: "ODT MONTHLY admin (injectable)",
            fundedRateDesc: "$22.15 /injection",
            fundedRate: 22.15,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Patients",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 1,
            calc: standardCalc,
        },
        {
            id: "thn",
            name: "Take Home Naloxone (THN)",
            fundedRateDesc: "$18.25 profit",
            fundedRate: 18.25,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 4,
            calc: standardCalc,
        },
    ],
    part2: [
        {
            id: "covid",
            name: "COVID-19 Vaccinations",
            fundedRateDesc: "$28.35",
            fundedRate: 28.35,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "/year",
            timeFactor: 1,
            currentVol: 500,
            potentialVol: 600,
            calc: standardCalc,
        },
        {
            id: "nipvip",
            name: "NIPVIP Vaccinations",
            fundedRateDesc: "$19.32",
            fundedRate: 19.32,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "/year",
            timeFactor: 1,
            currentVol: 50,
            potentialVol: 300,
            calc: standardCalc,
        },
        {
            id: "flu-comm",
            name: "Flu Community Patients",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 29,
            patientFeePotential: 29,
            unit: "/year",
            timeFactor: 1,
            currentVol: 500,
            potentialVol: 700,
            calc: standardCalc,
        },
        {
            id: "flu-corp",
            name: "Flu Corporate Program",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 20,
            unit: "/year",
            timeFactor: 1,
            currentVol: 50,
            potentialVol: 70,
            calc: standardCalc,
        },
        {
            id: "mmr",
            name: "MMR",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 20,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "dtpa",
            name: "dTpa",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 55,
            patientFeePotential: 55,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 50,
            calc: standardCalc,
        },
        {
            id: "dtpa-polio",
            name: "dTpa + poliovirus",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 55,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "polio",
            name: "Poliomyelitis",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 40,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "cholera",
            name: "Cholera",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 90,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 5,
            calc: standardCalc,
        },
        {
            id: "haemophilus",
            name: "Haemophilus influenzae type B",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 45,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "meningococcal",
            name: "Meningococcal",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 20,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "pneumococcal",
            name: "Pneumococcal",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 20,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 50,
            calc: standardCalc,
        },
        {
            id: "hepa",
            name: "Hepatitis A",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 70,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "shingles",
            name: "Shingles",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 220,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 20,
            calc: standardCalc,
        },
        {
            id: "hepb",
            name: "Hepatitis B",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 20,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 20,
            calc: standardCalc,
        },
        {
            id: "hpv",
            name: "HPV",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 20,
            patientFeePotential: 20,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 100,
            calc: standardCalc,
        },
        {
            id: "varicella",
            name: "Varicella",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 65,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "rsv",
            name: "RSV",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 300,
            unit: "/year",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 20,
            calc: standardCalc,
        },
    ],
    part3: [
        {
            id: "app-enrol",
            name: "App enrolments",
            fundedRateDesc: "$48/patient/yr",
            fundedRate: 48,
            patientFeeCurrent: 0,
            patientFeePotential: 0,
            unit: "Active Patients",
            timeFactor: 1,
            currentVol: 100,
            potentialVol: 150,
            calc: standardCalc,
        },
        {
            id: "uti",
            name: "UTI Consultation",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 25,
            patientFeePotential: 25,
            unit: "/month",
            timeFactor: 12,
            currentVol: 1,
            potentialVol: 4,
            calc: standardCalc,
        },
        {
            id: "ocp",
            name: "Resupply of OCP Consultation",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 30,
            patientFeePotential: 30,
            unit: "/month",
            timeFactor: 12,
            currentVol: 1,
            potentialVol: 4,
            calc: standardCalc,
        },
        {
            id: "skin",
            name: "Minor Skin Conditions Consultation",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 25,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "travel",
            name: "Travel Health Consultation",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 35,
            patientFeePotential: 35,
            unit: "/month",
            timeFactor: 12,
            currentVol: 1,
            potentialVol: 4,
            calc: standardCalc,
        },
        {
            id: "injection",
            name: "Administering Medicines by Injection",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 25,
            patientFeePotential: 25,
            unit: "/month",
            timeFactor: 12,
            currentVol: 1,
            potentialVol: 4,
            calc: standardCalc,
        },
        {
            id: "absence-cert",
            name: "Absence from Work Certificates",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 35,
            patientFeePotential: 35,
            unit: "/month",
            timeFactor: 12,
            currentVol: 2,
            potentialVol: 10,
            calc: standardCalc,
        },
        {
            id: "weight",
            name: "Weight Management Programs",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 50,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 5,
            calc: standardCalc,
        },
        {
            id: "sleep",
            name: "Sleep Studies",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 100,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 2,
            calc: standardCalc,
        },
        {
            id: "woundcare",
            name: "Woundcare",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 25,
            patientFeePotential: 25,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 4,
            calc: standardCalc,
        },
        {
            id: "delivery",
            name: "Home deliveries",
            fundedRateDesc: "N/A",
            fundedRate: 0,
            patientFeeCurrent: 0,
            patientFeePotential: 10,
            unit: "/month",
            timeFactor: 12,
            currentVol: 0,
            potentialVol: 20,
            calc: standardCalc,
        },
    ],
    part4: [
        {
            id: "ada-margin",
            name: "Adalimumab Additional Margin",
            fundedRateDesc: "$681.20/yr",
            fundedRate: 681.2,
            unit: "Patients",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 3,
            calc: (c, p, pfc, pfp, fr, tf) => [
                fr * c * tf,
                fr * (p - c) * tf,
            ],
        },
        {
            id: "ada-program",
            name: "Adalimumab: Pharmacy Program",
            fundedRateDesc: "$370/yr",
            fundedRate: 370,
            unit: "Patients",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 3,
            calc: (c, p, pfc, pfp, fr, tf) => [
                fr * c * tf,
                fr * (p - c) * tf,
            ],
        },
        {
            id: "eta-margin",
            name: "Etanercept NIS Saving",
            fundedRateDesc: "$790.27/yr",
            fundedRate: 790.27,
            unit: "Patients",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 1,
            calc: (c, p, pfc, pfp, fr, tf) => [
                fr * c * tf,
                fr * (p - c) * tf,
            ],
        },
        {
            id: "eta-program",
            name: "Etanercept: Pharmacy Program",
            fundedRateDesc: "$240/yr",
            fundedRate: 240,
            unit: "Patients",
            timeFactor: 1,
            currentVol: 0,
            potentialVol: 1,
            calc: (c, p, pfc, pfp, fr, tf) => [
                fr * c * tf,
                fr * (p - c) * tf,
            ],
        },
    ],
};
